site_name: LMSGI ASIX — Lenguajes de Marcas
site_description: Documentación en Markdown para 1º de ASIX (HTML, XML/DTD/XSD, XPath/XSLT, RSS, SVG, JSON)
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

# Configura tu repositorio para mostrar "Editar esta página":
# repo_url: https://github.com/tu-usuario/tu-repo
# edit_uri: edit/main/docs/

nav: 
  - Introducción: html.md
  - Tags y atributos: html_atributos.md
  - HTML-Práctica: practicas_html.md
  - Flex: html_flex.md
  - CSS: css.md
  - CSS-Práctica: css_practica.md
  - Referencias HTML&CSS: html_referencias.md
  - Javascript: js-intro.md
  - Javascript-Formularios: js-formularios.md
  - Javascript-Práctica: js-formularios-practica.md
  - Javascript-Referencias: js-formularios-referencias.md


#  - XML + DTD + XSD: xml_dtd_xsd.md
#  - XPath & XSLT: xpath_xslt.md
#  - SVG: svg.md
#  - JSON: json.md
#  - Retos: retos.md

plugins:
 - mermaid2:
      version: 10.0.2
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
 - search:
      lang: es     # opcional: mejora el buscador para español

extra_css:
  - css/base.css


markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - admonition

