site_name: LMSGI ASIX — Lenguajes de Marcas
site_description: Documentación en Markdown para 1º de ASIX (HTML, XML/DTD/XSD, XPath/XSLT, RSS, SVG, JSON)
docs_dir: PHP_JSON
site_dir: PHP_SITE
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Modo claro

# Configura tu repositorio para mostrar "Editar esta página":
# repo_url: https://github.com/tu-usuario/tu-repo
# edit_uri: edit/main/docs/

nav: 
index: index.md
PHP:
  - Introducción: php1.md
  - Variables y arrays simples: php2.md
  - Arrays asociativos y JSON: php3.md
  - Integración con HTML y Js: php4.md
  - Flujo Cliente-Serivodr: php5.md
  - Proyecto integrador: php_proyecto.md
  - Referencias: php_referencias.md


#  - XML + DTD + XSD: xml_dtd_xsd.md
#  - XPath & XSLT: xpath_xslt.md
#  - SVG: svg.md
#  - JSON: json.md
#  - Retos: retos.md

plugins:
 - mermaid2:
      version: 10.0.2
      javascript: https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
 - search:
      lang: es     # opcional: mejora el buscador para español

extra_css:
  - css/base.css


markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
  - admonition

